// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8jSn2n5NwQkqH9pfFWOjbzYqLqqbXPNk',
    appId: '1:119927273750:web:79219854e99d13b20af837',
    messagingSenderId: '119927273750',
    projectId: 'my-keep-371508',
    authDomain: 'my-keep-371508.firebaseapp.com',
    storageBucket: 'my-keep-371508.appspot.com',
    measurementId: 'G-C2N4Q3YF66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdP5niXKv-_Jj_L-JAi8w-37moZdVjUsI',
    appId: '1:119927273750:android:8dce1d9a7c97530f0af837',
    messagingSenderId: '119927273750',
    projectId: 'my-keep-371508',
    storageBucket: 'my-keep-371508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ8DQkfyjzHp1gsY09ag4rqN-S7X1ITgo',
    appId: '1:119927273750:ios:d4f0a6885fd3007f0af837',
    messagingSenderId: '119927273750',
    projectId: 'my-keep-371508',
    storageBucket: 'my-keep-371508.appspot.com',
    iosBundleId: 'com.example.rc168',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ8DQkfyjzHp1gsY09ag4rqN-S7X1ITgo',
    appId: '1:119927273750:ios:4429e2881f5395780af837',
    messagingSenderId: '119927273750',
    projectId: 'my-keep-371508',
    storageBucket: 'my-keep-371508.appspot.com',
    iosBundleId: 'com.example.rc168.RunnerTests',
  );
}
