// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzLX9TQQjQulaTFBJhS5yUVnO9Y10Ar5Y',
    appId: '1:841434982717:web:2fc38bd8ee9cc1d568bd54',
    messagingSenderId: '841434982717',
    projectId: 'test-fcm-72314',
    authDomain: 'test-fcm-72314.firebaseapp.com',
    storageBucket: 'test-fcm-72314.appspot.com',
    measurementId: 'G-DL9S3Z3ZDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-RpwJ3DdvwbvT180rn4kfmCk7TkG0ZvA',
    appId: '1:841434982717:android:51e176a492d5e9b968bd54',
    messagingSenderId: '841434982717',
    projectId: 'test-fcm-72314',
    storageBucket: 'test-fcm-72314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF2pg89FWBJ_4A8VfEZ-hBoLwkSQ9obSI',
    appId: '1:841434982717:ios:f0c7fb71712479fc68bd54',
    messagingSenderId: '841434982717',
    projectId: 'test-fcm-72314',
    storageBucket: 'test-fcm-72314.appspot.com',
    iosBundleId: 'com.example.rc168',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF2pg89FWBJ_4A8VfEZ-hBoLwkSQ9obSI',
    appId: '1:841434982717:ios:b897a36c9f98753968bd54',
    messagingSenderId: '841434982717',
    projectId: 'test-fcm-72314',
    storageBucket: 'test-fcm-72314.appspot.com',
    iosBundleId: 'com.example.rc168.RunnerTests',
  );
}
