// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6-ra6Pg2Yh4O_UyHFtzeqx8XOBM2RpTE',
    appId: '1:820244556849:web:bab356fd5f76111dfb7910',
    messagingSenderId: '820244556849',
    projectId: 'fcm-rc168',
    authDomain: 'fcm-rc168.firebaseapp.com',
    storageBucket: 'fcm-rc168.appspot.com',
    measurementId: 'G-FPSCW6VSER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ81SudJ17nne0KKsOHoLSsvr7dlty7kM',
    appId: '1:820244556849:android:910aecd4d3aa2794fb7910',
    messagingSenderId: '820244556849',
    projectId: 'fcm-rc168',
    storageBucket: 'fcm-rc168.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY2AHrlEGc4J7EpcjsfC7Y8EAmgE2-x9w',
    appId: '1:820244556849:ios:7b6623035d277678fb7910',
    messagingSenderId: '820244556849',
    projectId: 'fcm-rc168',
    storageBucket: 'fcm-rc168.appspot.com',
    iosBundleId: 'com.rc168.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY2AHrlEGc4J7EpcjsfC7Y8EAmgE2-x9w',
    appId: '1:820244556849:ios:8da976988d55ad59fb7910',
    messagingSenderId: '820244556849',
    projectId: 'fcm-rc168',
    storageBucket: 'fcm-rc168.appspot.com',
    iosBundleId: 'com.rc168.app.RunnerTests',
  );
}
